#!/usr/bin/env python3
"""YiCore build info gen utility.

Author: Don
Date: 2026-07-26
Version: 1.0.0
"""

import argparse
import datetime as dt
import os
from pathlib import Path


def _build_datetime():
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch is not None:
        return dt.datetime.fromtimestamp(int(epoch), tz=dt.timezone.utc)
    return dt.datetime.now().astimezone()


def _c_string(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate(image, version, output, timestamp=None):
    if not image or len(image.encode("ascii")) > 15:
        raise ValueError("image must be 1-15 ASCII characters")
    if not version or len(version.encode("ascii")) > 31:
        raise ValueError("version must be 1-31 ASCII characters")

    timestamp = timestamp or _build_datetime()
    source = f'''/* Generated by yi_build_info_gen.py. Do not edit. */
#include "yi_build_info.h"

__attribute__((used, section(".yi_build_info")))
const yi_build_info_t yi_build_info =
{{
    .magic = YI_BUILD_INFO_MAGIC,
    .format_version = YI_BUILD_INFO_FORMAT_VERSION,
    .size = sizeof(yi_build_info_t),
    .image = "{_c_string(image)}",
    .version = "{_c_string(version)}",
    .build_date = "{timestamp:%Y-%m-%d}",
    .build_time = "{timestamp:%H:%M:%S}",
}};
'''
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser(description="Generate YiCore image build metadata")
    parser.add_argument("--image", required=True)
    parser.add_argument("--version-file", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    version = args.version_file.read_text(encoding="utf-8").strip()
    generate(args.image, version, args.output)
    print(args.output)


if __name__ == "__main__":
    main()
