#!/usr/bin/env python3
"""Generate Zephyr-style YiCore configuration outputs with Kconfiglib.

Author: Don
Date: 2026-08-02
Version: 1.0.0
"""

from __future__ import annotations

import os
from pathlib import Path

import kconfiglib


class ConfigurationError(ValueError):
    """Report an unavailable Kconfig tree or invalid configuration fragment."""


def generate_configuration(
    yicore_root: Path,
    build_dir: Path,
    fragments: list[Path] | None = None,
) -> dict[str, Path]:
    """Merge configuration fragments and generate standard build artifacts.

    Args:
        yicore_root: YiCore repository containing the root Kconfig file.
        build_dir: Application build directory.
        fragments: Ordered existing prj.conf/board.conf-style fragments.
    Returns:
        Paths for dotconfig, autoconf header, and generated CMake settings.
    Side effects:
        Creates build/yicore configuration files below build_dir.
    Raises:
        ConfigurationError: Kconfig or a requested fragment is unavailable.
    """

    root_kconfig = yicore_root / "Kconfig"
    if not root_kconfig.is_file():
        raise ConfigurationError(f"YiCore Kconfig not found: {root_kconfig}")
    selected_fragments = fragments or []
    missing_fragments = [path for path in selected_fragments if not path.is_file()]
    if missing_fragments:
        raise ConfigurationError(
            f"configuration fragment not found: {missing_fragments[0]}"
        )
    output_root = build_dir / "yicore"
    generated_include = output_root / "include" / "generated"
    output_root.mkdir(parents=True, exist_ok=True)
    generated_include.mkdir(parents=True, exist_ok=True)
    previous_srctree = os.environ.get("srctree")
    os.environ["srctree"] = str(yicore_root.resolve())
    try:
        configuration = kconfiglib.Kconfig(str(root_kconfig), warn=False)
        for index, fragment in enumerate(selected_fragments):
            configuration.load_config(
                str(fragment), replace=index == 0
            )
        dotconfig = output_root / ".config"
        autoconf = generated_include / "autoconf.h"
        configuration.write_config(str(dotconfig))
        configuration.write_autoconf(str(autoconf))
        cmake_config = output_root / "kconfig.cmake"
        cmake_lines = [
            "# Generated by yi_kconfig.py; do not edit.\n"
        ]
        for symbol in configuration.unique_defined_syms:
            if symbol.name and symbol.str_value:
                cmake_lines.append(
                    f'set(CONFIG_{symbol.name} "{symbol.str_value}")\n'
                )
        cmake_config.write_text(
            "".join(cmake_lines), encoding="utf-8", newline="\n"
        )
    finally:
        if previous_srctree is None:
            os.environ.pop("srctree", None)
        else:
            os.environ["srctree"] = previous_srctree
    return {
        "dotconfig": dotconfig,
        "autoconf": autoconf,
        "cmake": cmake_config,
        "include": generated_include,
    }


def discover_fragments(source_dir: Path, board: str | None = None) -> list[Path]:
    """Return existing Zephyr-style configuration fragments in merge order.

    Args:
        source_dir: Application or product image directory.
        board: Optional board identifier used for boards/<board>.conf.
    Returns:
        Existing board and application fragments, with application last.
    """

    candidates: list[Path] = []
    if board:
        candidates.append(source_dir / "boards" / f"{board}.conf")
    candidates.append(source_dir / "prj.conf")
    return [candidate for candidate in candidates if candidate.is_file()]

